name: CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: yarn install
              run: yarn install --frozen-lockfile

            - name: lint
              run: npm run lint

            - name: build
              run: npm run build

            - name: set git
              run: git config --global user.email "altinok.darici@gmail.com" &&  git config --global user.name "altinokdarici" &&  git remote set-url origin "https://altinokdarici:$GIT_PAT@github.com/altinokdarici/modern-stack.git"
              env:
                  GIT_PAT: ${{ secrets.GIT_PAT }}

            - name: publish
              run: npm run beachball:publish -- -n $NPM_TOKEN
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
